name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: for d in go/*/ ; do (cd "$d" && go build ./...); done

      - name: Test
        run: for d in go/*/ ; do (cd "$d" && go test ./...); done

      - name: Benchmark
        run: for d in go/*/ ; do (cd "$d" && go test -v --bench --benchmem ./...); done

      - name: Vet
        run: for d in go/*/ ; do (cd "$d" && go vet ./...); done

      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
        with:
          path: "./go/..."
        continue-on-error: true
      - name: Run staticcheck with reviewdog
        uses: reviewdog/action-staticcheck@v1
        with:
          fail_on_error: true



