name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: for d in go/*/ ; do (cd "$d" && go build ./...); done

      - name: Test
        run: for d in go/*/ ; do (cd "$d" && go test ./...); done

      - name: Benchmark
        run: for d in go/*/ ; do (cd "$d" && go test -v --bench --benchmem ./...); done

      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.0
          for d in go/*/ ; do (cd "$d" && golangci-lint run); done



