name: Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Gradle package task
        run: for d in java/*/ ; do (cd "$d" && gradle -q assemble); done
      - name: Run the Gradle check task
        run: for d in java/*/ ; do (cd "$d" && gradle -q check spotbugsMain spotbugsTest checkstyleMain checkstyleTest); done
      - name: Run the Gradle dependency task
        run: for d in java/*/ ; do ( cd "$d" && gradle -DgradleReleaseChannel=current dependencyUpdates | grep "\\->"  && (test $? -ne 0 || echo "$d") ) ; done
