# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        for d in python/*/ ; do (cd "$d" && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics); done
        
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        for d in python/*/ ; do (cd "$d" && flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics); done
        
    - name: Analysing the code with pylint
      run: |
        for d in python/*/ ; do (cd "$d" && pylint $(git ls-files '*.py')); done
        
    - name: Test with pytest
      run: |
        for d in python/*/ ; do (cd "$d" && pytest); done


        

